# Generated by Django 4.1.6 on 2023-02-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_options_alter_bookcomments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
