# Generated by Django 4.1.6 on 2023-02-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
