# Generated by Django 4.1.6 on 2023-02-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='book.author'),
        ),
    ]
